// src/components/react/react-button.jsx
import { useState } from 'react'

const ReactBtn = () => {
    const [count, setCount] = useState(0);

    const addCount = () => {
        setCount(count + 1);
    }

    return (
        <div className='flex flex-col'>
            <h2 className='text-4xl font-bold text-blue-500'>
                React
            </h2>
            <div className='pt-6'>
                <p className='pb-4 text-xl text-white'>
                    Count: {count}
                </p>
                <button className='px-2 py-1 text-white bg-blue-500 rounded-lg hover:bg-blue-600' onClick={() => addCount()}
                >
                    React Button
                </button>
            </div>
        </div>
    )
};

export default ReactBtn;

// src/components/lit/lit-button.js
import { LitElement, css, html } from "lit";

export class LitBtn extends LitElement {
    static properties = {
        _count: {type: Number},
    };

    constructor() {
        super();
        this._count = 0;
    }

    render() {
        return html`
            <div class="flex flex-col">
                <h2 class="text-4xl font-bold text-blue-700">Lit</h2>
                <div class="pt-6">
                    <p class="pb-4 text-xl text-white">
                        Count: ${this._count}
                    </p>
                    <button class="px-2 py-1 text-white bg-blue-700 rounded-lg hover:bg-blue-800" @click=${this._increment}>
                        Lit Button
                    </button>
                </div>
            </div>
        `;
    }
    _increment(e) {
        this._count++;
        this.requestUpdate(); // プロパティの変更を通知
    }
}

customElements.define('lit-btn', LitBtn);
