// src/components/svelte/svelte-button.svelte
<script>
    let count = 0;
    function addCount() {
        count += 1;
    }
</script>

<div class="flex flex-col">
    <h2 class="text-4xl font-bold text-orange-500">
        Svelte
    </h2>
    <div class="pt-6">
        <p class="pb-4 text-xl text-white">
            Count: {count}
        </p>
        <button class="px-2 py-1 text-white bg-orange-500 rounded-lg hover:bg-orange-600" on:click={addCount}>
            Svelte Button
        </button>
    </div>
</div>

// src/components/react/react-button.jsx
import { useState } from 'react'

const ReactBtn = () => {
    const [count, setCount] = useState(0);

    const addCount = () => {
        setCount(count + 1);
    }

    return (
        <div className='flex flex-col'>
            <h2 className='text-4xl font-bold text-blue-500'>
                React
            </h2>
            <div className='pt-6'>
                <p className='pb-4 text-xl text-white'>
                    Count: {count}
                </p>
                <button className='px-2 py-1 text-white bg-blue-500 rounded-lg hover:bg-blue-600' onClick={() => addCount()}
                >
                    React Button
                </button>
            </div>
        </div>
    )
};

export default ReactBtn;
